// Generated by gencpp from file turtle_interfaces/TurtleFollow.msg
// DO NOT EDIT!


#ifndef TURTLE_INTERFACES_MESSAGE_TURTLEFOLLOW_H
#define TURTLE_INTERFACES_MESSAGE_TURTLEFOLLOW_H

#include <ros/service_traits.h>


#include <turtle_interfaces/TurtleFollowRequest.h>
#include <turtle_interfaces/TurtleFollowResponse.h>


namespace turtle_interfaces
{

struct TurtleFollow
{

typedef TurtleFollowRequest Request;
typedef TurtleFollowResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TurtleFollow
} // namespace turtle_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtle_interfaces::TurtleFollow > {
  static const char* value()
  {
    return "78f97197b9a4b2024f26e6a6f492efd7";
  }

  static const char* value(const ::turtle_interfaces::TurtleFollow&) { return value(); }
};

template<>
struct DataType< ::turtle_interfaces::TurtleFollow > {
  static const char* value()
  {
    return "turtle_interfaces/TurtleFollow";
  }

  static const char* value(const ::turtle_interfaces::TurtleFollow&) { return value(); }
};


// service_traits::MD5Sum< ::turtle_interfaces::TurtleFollowRequest> should match
// service_traits::MD5Sum< ::turtle_interfaces::TurtleFollow >
template<>
struct MD5Sum< ::turtle_interfaces::TurtleFollowRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_interfaces::TurtleFollow >::value();
  }
  static const char* value(const ::turtle_interfaces::TurtleFollowRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_interfaces::TurtleFollowRequest> should match
// service_traits::DataType< ::turtle_interfaces::TurtleFollow >
template<>
struct DataType< ::turtle_interfaces::TurtleFollowRequest>
{
  static const char* value()
  {
    return DataType< ::turtle_interfaces::TurtleFollow >::value();
  }
  static const char* value(const ::turtle_interfaces::TurtleFollowRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtle_interfaces::TurtleFollowResponse> should match
// service_traits::MD5Sum< ::turtle_interfaces::TurtleFollow >
template<>
struct MD5Sum< ::turtle_interfaces::TurtleFollowResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_interfaces::TurtleFollow >::value();
  }
  static const char* value(const ::turtle_interfaces::TurtleFollowResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_interfaces::TurtleFollowResponse> should match
// service_traits::DataType< ::turtle_interfaces::TurtleFollow >
template<>
struct DataType< ::turtle_interfaces::TurtleFollowResponse>
{
  static const char* value()
  {
    return DataType< ::turtle_interfaces::TurtleFollow >::value();
  }
  static const char* value(const ::turtle_interfaces::TurtleFollowResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLE_INTERFACES_MESSAGE_TURTLEFOLLOW_H
