// Generated by gencpp from file turtle_interfaces/TurtleCreate.msg
// DO NOT EDIT!


#ifndef TURTLE_INTERFACES_MESSAGE_TURTLECREATE_H
#define TURTLE_INTERFACES_MESSAGE_TURTLECREATE_H

#include <ros/service_traits.h>


#include <turtle_interfaces/TurtleCreateRequest.h>
#include <turtle_interfaces/TurtleCreateResponse.h>


namespace turtle_interfaces
{

struct TurtleCreate
{

typedef TurtleCreateRequest Request;
typedef TurtleCreateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TurtleCreate
} // namespace turtle_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtle_interfaces::TurtleCreate > {
  static const char* value()
  {
    return "72760cab38314f5e1f8f9a7e416953a8";
  }

  static const char* value(const ::turtle_interfaces::TurtleCreate&) { return value(); }
};

template<>
struct DataType< ::turtle_interfaces::TurtleCreate > {
  static const char* value()
  {
    return "turtle_interfaces/TurtleCreate";
  }

  static const char* value(const ::turtle_interfaces::TurtleCreate&) { return value(); }
};


// service_traits::MD5Sum< ::turtle_interfaces::TurtleCreateRequest> should match
// service_traits::MD5Sum< ::turtle_interfaces::TurtleCreate >
template<>
struct MD5Sum< ::turtle_interfaces::TurtleCreateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_interfaces::TurtleCreate >::value();
  }
  static const char* value(const ::turtle_interfaces::TurtleCreateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_interfaces::TurtleCreateRequest> should match
// service_traits::DataType< ::turtle_interfaces::TurtleCreate >
template<>
struct DataType< ::turtle_interfaces::TurtleCreateRequest>
{
  static const char* value()
  {
    return DataType< ::turtle_interfaces::TurtleCreate >::value();
  }
  static const char* value(const ::turtle_interfaces::TurtleCreateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtle_interfaces::TurtleCreateResponse> should match
// service_traits::MD5Sum< ::turtle_interfaces::TurtleCreate >
template<>
struct MD5Sum< ::turtle_interfaces::TurtleCreateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_interfaces::TurtleCreate >::value();
  }
  static const char* value(const ::turtle_interfaces::TurtleCreateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_interfaces::TurtleCreateResponse> should match
// service_traits::DataType< ::turtle_interfaces::TurtleCreate >
template<>
struct DataType< ::turtle_interfaces::TurtleCreateResponse>
{
  static const char* value()
  {
    return DataType< ::turtle_interfaces::TurtleCreate >::value();
  }
  static const char* value(const ::turtle_interfaces::TurtleCreateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLE_INTERFACES_MESSAGE_TURTLECREATE_H
