(cl:defpackage turtle_interfaces-srv
  (:use )
  (:export
   "TURTLECREATE"
   "<TURTLECREATE-REQUEST>"
   "TURTLECREATE-REQUEST"
   "<TURTLECREATE-RESPONSE>"
   "TURTLECREATE-RESPONSE"
   "TURTLEFOLLOW"
   "<TURTLEFOLLOW-REQUEST>"
   "TURTLEFOLLOW-REQUEST"
   "<TURTLEFOLLOW-RESPONSE>"
   "TURTLEFOLLOW-RESPONSE"
  ))

