// Generated by gencpp from file turtle_control/TurtleFollowResponse.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROL_MESSAGE_TURTLEFOLLOWRESPONSE_H
#define TURTLE_CONTROL_MESSAGE_TURTLEFOLLOWRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_control
{
template <class ContainerAllocator>
struct TurtleFollowResponse_
{
  typedef TurtleFollowResponse_<ContainerAllocator> Type;

  TurtleFollowResponse_()
    : status()  {
    }
  TurtleFollowResponse_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::turtle_control::TurtleFollowResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_control::TurtleFollowResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleFollowResponse_

typedef ::turtle_control::TurtleFollowResponse_<std::allocator<void> > TurtleFollowResponse;

typedef boost::shared_ptr< ::turtle_control::TurtleFollowResponse > TurtleFollowResponsePtr;
typedef boost::shared_ptr< ::turtle_control::TurtleFollowResponse const> TurtleFollowResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_control::TurtleFollowResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_control::TurtleFollowResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_control::TurtleFollowResponse_<ContainerAllocator1> & lhs, const ::turtle_control::TurtleFollowResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_control::TurtleFollowResponse_<ContainerAllocator1> & lhs, const ::turtle_control::TurtleFollowResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_control::TurtleFollowResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_control::TurtleFollowResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control::TurtleFollowResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control::TurtleFollowResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control::TurtleFollowResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control::TurtleFollowResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_control::TurtleFollowResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::turtle_control::TurtleFollowResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_control::TurtleFollowResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_control/TurtleFollowResponse";
  }

  static const char* value(const ::turtle_control::TurtleFollowResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_control::TurtleFollowResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string status\n"
;
  }

  static const char* value(const ::turtle_control::TurtleFollowResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_control::TurtleFollowResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleFollowResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_control::TurtleFollowResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_control::TurtleFollowResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CONTROL_MESSAGE_TURTLEFOLLOWRESPONSE_H
