// Generated by gencpp from file turtle_control/TurtleFollow.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROL_MESSAGE_TURTLEFOLLOW_H
#define TURTLE_CONTROL_MESSAGE_TURTLEFOLLOW_H

#include <ros/service_traits.h>


#include <turtle_control/TurtleFollowRequest.h>
#include <turtle_control/TurtleFollowResponse.h>


namespace turtle_control
{

struct TurtleFollow
{

typedef TurtleFollowRequest Request;
typedef TurtleFollowResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TurtleFollow
} // namespace turtle_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtle_control::TurtleFollow > {
  static const char* value()
  {
    return "78f97197b9a4b2024f26e6a6f492efd7";
  }

  static const char* value(const ::turtle_control::TurtleFollow&) { return value(); }
};

template<>
struct DataType< ::turtle_control::TurtleFollow > {
  static const char* value()
  {
    return "turtle_control/TurtleFollow";
  }

  static const char* value(const ::turtle_control::TurtleFollow&) { return value(); }
};


// service_traits::MD5Sum< ::turtle_control::TurtleFollowRequest> should match
// service_traits::MD5Sum< ::turtle_control::TurtleFollow >
template<>
struct MD5Sum< ::turtle_control::TurtleFollowRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_control::TurtleFollow >::value();
  }
  static const char* value(const ::turtle_control::TurtleFollowRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_control::TurtleFollowRequest> should match
// service_traits::DataType< ::turtle_control::TurtleFollow >
template<>
struct DataType< ::turtle_control::TurtleFollowRequest>
{
  static const char* value()
  {
    return DataType< ::turtle_control::TurtleFollow >::value();
  }
  static const char* value(const ::turtle_control::TurtleFollowRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtle_control::TurtleFollowResponse> should match
// service_traits::MD5Sum< ::turtle_control::TurtleFollow >
template<>
struct MD5Sum< ::turtle_control::TurtleFollowResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_control::TurtleFollow >::value();
  }
  static const char* value(const ::turtle_control::TurtleFollowResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_control::TurtleFollowResponse> should match
// service_traits::DataType< ::turtle_control::TurtleFollow >
template<>
struct DataType< ::turtle_control::TurtleFollowResponse>
{
  static const char* value()
  {
    return DataType< ::turtle_control::TurtleFollow >::value();
  }
  static const char* value(const ::turtle_control::TurtleFollowResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLE_CONTROL_MESSAGE_TURTLEFOLLOW_H
