// Generated by gencpp from file turtle_control/TurtleCreate.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROL_MESSAGE_TURTLECREATE_H
#define TURTLE_CONTROL_MESSAGE_TURTLECREATE_H

#include <ros/service_traits.h>


#include <turtle_control/TurtleCreateRequest.h>
#include <turtle_control/TurtleCreateResponse.h>


namespace turtle_control
{

struct TurtleCreate
{

typedef TurtleCreateRequest Request;
typedef TurtleCreateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TurtleCreate
} // namespace turtle_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtle_control::TurtleCreate > {
  static const char* value()
  {
    return "72760cab38314f5e1f8f9a7e416953a8";
  }

  static const char* value(const ::turtle_control::TurtleCreate&) { return value(); }
};

template<>
struct DataType< ::turtle_control::TurtleCreate > {
  static const char* value()
  {
    return "turtle_control/TurtleCreate";
  }

  static const char* value(const ::turtle_control::TurtleCreate&) { return value(); }
};


// service_traits::MD5Sum< ::turtle_control::TurtleCreateRequest> should match
// service_traits::MD5Sum< ::turtle_control::TurtleCreate >
template<>
struct MD5Sum< ::turtle_control::TurtleCreateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_control::TurtleCreate >::value();
  }
  static const char* value(const ::turtle_control::TurtleCreateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_control::TurtleCreateRequest> should match
// service_traits::DataType< ::turtle_control::TurtleCreate >
template<>
struct DataType< ::turtle_control::TurtleCreateRequest>
{
  static const char* value()
  {
    return DataType< ::turtle_control::TurtleCreate >::value();
  }
  static const char* value(const ::turtle_control::TurtleCreateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtle_control::TurtleCreateResponse> should match
// service_traits::MD5Sum< ::turtle_control::TurtleCreate >
template<>
struct MD5Sum< ::turtle_control::TurtleCreateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_control::TurtleCreate >::value();
  }
  static const char* value(const ::turtle_control::TurtleCreateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_control::TurtleCreateResponse> should match
// service_traits::DataType< ::turtle_control::TurtleCreate >
template<>
struct DataType< ::turtle_control::TurtleCreateResponse>
{
  static const char* value()
  {
    return DataType< ::turtle_control::TurtleCreate >::value();
  }
  static const char* value(const ::turtle_control::TurtleCreateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLE_CONTROL_MESSAGE_TURTLECREATE_H
